#!/usr/bin/env python3
"""
Gmail API Token Generator
This script authorizes your app to send emails via Gmail API
"""

import os
import json
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
import pickle

SCOPES = ['https://www.googleapis.com/auth/gmail.send']


def main():
    print("=" * 70)
    print("  Gmail API Token Generator")
    print("  For YouTube News Scraper")
    print("=" * 70)
    print()

    creds = None

    # Check if credentials.json exists
    if not os.path.exists('credentials.json'):
        print("❌ ERROR: credentials.json not found!")
        print()
        print("Please download it from Google Cloud Console:")
        print("1. Go to https://console.cloud.google.com/apis/credentials")
        print("2. Create OAuth 2.0 Client ID (Desktop app)")
        print("3. Download JSON and save as 'credentials.json'")
        print()
        return

    print("✅ Found credentials.json")
    print()

    # The file token.pickle stores the user's access and refresh tokens
    if os.path.exists('token.pickle'):
        print("📄 Found existing token.pickle")
        with open('token.pickle', 'rb') as token:
            creds = pickle.load(token)

    # If there are no (valid) credentials available, let the user log in
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            print("🔄 Refreshing expired token...")
            creds.refresh(Request())
        else:
            print("🔐 Starting OAuth flow...")
            print("Your browser will open - please log in and authorize the app")
            print()
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)

        # Save the credentials for the next run
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)
        print("✅ Token saved to token.pickle")

    print()
    print("=" * 70)
    print("  ✅ AUTHORIZATION SUCCESSFUL!")
    print("=" * 70)
    print()

    # Extract token info
    token_info = {
        'token': creds.token,
        'refresh_token': creds.refresh_token,
        'token_uri': creds.token_uri,
        'client_id': creds.client_id,
        'client_secret': creds.client_secret,
        'scopes': creds.scopes
    }

    # Read credentials.json
    with open('credentials.json', 'r') as f:
        creds_data = json.load(f)

    # Format for Railway
    creds_json = json.dumps(creds_data)
    token_json = json.dumps(token_info)

    print("📋 RAILWAY ENVIRONMENT VARIABLES")
    print("=" * 70)
    print()
    print("Copy and run these commands:")
    print()
    print(f"railway variables --set 'GMAIL_CREDENTIALS_JSON={creds_json}'")
    print()
    print(f"railway variables --set 'GMAIL_TOKEN_JSON={token_json}'")
    print()
    print("=" * 70)
    print()

    # Save to .env for local testing
    env_path = '.env'
    env_exists = os.path.exists(env_path)

    # Read existing .env
    existing_lines = []
    if env_exists:
        with open(env_path, 'r') as f:
            existing_lines = [line for line in f.readlines()
                            if not line.startswith('GMAIL_CREDENTIALS_JSON')
                            and not line.startswith('GMAIL_TOKEN_JSON')]

    # Write updated .env
    with open(env_path, 'w') as f:
        f.writelines(existing_lines)
        if existing_lines and not existing_lines[-1].endswith('\n'):
            f.write('\n')
        f.write(f"\n# Gmail API Credentials (Generated by generate_gmail_token.py)\n")
        f.write(f"GMAIL_CREDENTIALS_JSON='{creds_json}'\n")
        f.write(f"GMAIL_TOKEN_JSON='{token_json}'\n")

    print("✅ Credentials saved to .env for local testing")
    print()
    print("=" * 70)
    print("  NEXT STEPS")
    print("=" * 70)
    print()
    print("1. Set the Railway variables (commands above)")
    print("2. Test locally:")
    print("   python app.py")
    print("   curl -X POST -H 'Content-Type: application/json' -d '{}' http://localhost:3000/api/test-email")
    print()
    print("3. Deploy to Railway:")
    print("   railway up")
    print()
    print("4. Test on Railway:")
    print("   curl -X POST -H 'Content-Type: application/json' -d '{}' https://your-app.railway.app/api/test-email")
    print()
    print("🎉 Your Gmail API is ready to use!")
    print()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Cancelled by user")
    except Exception as e:
        print(f"\n\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
